### ISSUE TITLE
Filters unintentionally block streams on twitch.tv

### ISSUE THREAD

**Issue by Andriamanitra** [finnish-easylist-addition/finnish-easylist-addition#427] opened 2022-09-28 01:59 UTC
### List the website(s) you're having issues:

https://twitch.tv/adorable_kittens

### What happens?

The video element gets entirely blocked due to broken rules in the list.

### Your settings

- OS/version: Linux
- Browser/version: Firefox 104.0.2
- Adblock Extension/version: uBlock Origin 1.44.5b5

### Other details:

What I suspect is happening is that some rules which don't have quotes around the class names get turned into rules like 
![image](https://user-images.githubusercontent.com/10672443/192669869-2e4f737a-6b24-4c1a-905b-399251efdbfd.png)
 which ends up blocking unintended elements. The problematic rules are found here:

https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/d575c769b348234e8bfcb9af8cd20036539efe7b/Finland_adb.txt#L107-L113

Disabling these rules (or adding quotes) fixed the issue for me.

**Comment by peace2000** [comment] 2022-09-28 03:48
Do all of those rules turn into that "undefined" rule? This issue is probably caused by this change in uBlock Origin: https://github.com/gorhill/uBlock/commit/a71b71e4c8a2037fc68970bc8912a76732edaade
I'll check this later later today.

**Comment by Andriamanitra** [comment] 2022-09-28 04:30
With some more testing I managed to narrow it down to just these two:
```
##div[class*=element--nativead] 
##div[class*=newsFrontAd]
```

**Comment by peace2000** [comment] 2022-09-28 08:13
I can't repro on Twitch but I can repro on `https://outlook.live.com/`

**Comment by peace2000** [comment] 2022-09-28 20:37
This should be fixed now, download the latest test version of uBO.

@Andriamanitra

**Comment by peace2000** [comment] 2022-09-30 12:28
Fixed.

**Closed by peace2000** 2022-09-30 12:28 UTC
