### ISSUE TITLE
HappyPancake anti-adblock

### ISSUE THREAD

**Issue by Antsa92** [finnish-easylist-addition/finnish-easylist-addition#266] opened 2020-12-10 23:59 UTC
This website have Anti-Adblock witch i need to watch advertisements to use discover on that website. Can that add to list so i can use website normal and it not say i have disable adblock?

**Comment by peace2000** [comment] 2020-12-13 14:32
I have seen reports concerning anti adblock on that site but the problem is that I cannot reproduce that.

Can you give steps how to reproduce that? What browser, Adblocker extension and lists you are using?

**Comment by Antsa92** [comment] 2020-12-13 15:39
I use Google Chrome, and use uBlock. On this picture can see what filters i use and how anti-adblock works. https://imgur.com/a/8G0iE2C

If i discovery users or try to send message, i got anti-adblock message.

**Comment by peace2000** [comment] 2020-12-13 16:10
If you update all your filter lists and refresh the page by pressing Ctrl + R do you still have that issue (Ctrl + R bypasses the cache)

Can you also post a screenshot of Ubo's logger?

(You can copy paste images directly to conversations on Github)

**Comment by peace2000** [comment] 2020-12-13 16:17
Does that anti adblock nag appear when you open a conversation with someone or only after you click "Send" a message?

**Comment by Antsa92** [comment] 2020-12-13 17:25
Still issue even i updated filters and updates website. Adblock nag apperar when i click "Send" a message.

19:22:25​​​ www.happypancake.fi​ 1 ​xhr ​https://api.happypancake.fi/profile/3f817bc2-f861-4e6d-a4fb-304614ae4581?type=simple

**Comment by peace2000** [comment] 2020-12-13 17:31
I have a test profile for that site but I'd rather not send messages to random people. If you don't mind, could you share your own profile link so I could try to send messages to you for testing purposes? I cannot otherwise analyze this. Those requests in those screenshots don't help in this case.

**Comment by peace2000** [comment] 2020-12-13 18:07
Wait that site does not allow to see profile id searching it from the source code :D

Just send message to my test account: https://www.happypancake.fi/profile?id=84431db1-6e98-4db4-8a54-0dcf87399845

**Comment by peace2000** [comment] 2020-12-13 18:32
Having exactly the same filters, browser and lists I still don't have that nag. Strange.

Would this filter help you? It's taken from Swedish list.

`happypancake.fi##+js(aopr, Object.prototype.adUnits)`

**Comment by Antsa92** [comment] 2020-12-13 18:40
Yes that worked. But that need add to uBlock filters so that can everyone use.

**Comment by peace2000** [comment] 2020-12-13 19:48
I'll add that rule to the Finnish Easylist. Strange that I couldn't reproduce it but clearly that rule is needed.

**Comment by peace2000** [comment] 2020-12-13 19:51
Fixed in https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/24d34a9beda70a5271256b4cd2983fd43b6b9521

**Closed by peace2000** 2020-12-13 19:51 UTC
